package com.mycompany.proyectofinal;

import java.awt.Font;
import java.awt.font.TextAttribute;
import java.util.Map;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author daa
 */
public class CreacionUsuarioCliente extends javax.swing.JFrame {

    public CreacionUsuarioCliente() {
        initComponents();
    }
    private boolean volver;
    
    public void RegresarInicio(){
        Inicio ventanaInicio = new Inicio();
        ventanaInicio.setVisible(true);
        this.dispose(); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Ingresar = new javax.swing.JLabel();
        textoConstCliente = new javax.swing.JComboBox<>();
        textoNombre = new javax.swing.JTextField();
        textoContraseña = new javax.swing.JTextField();
        textoVerificacionContraseña = new javax.swing.JTextField();
        enviarNuevoUsuario = new javax.swing.JButton();
        CuerpoCrearCuenta = new javax.swing.JLabel();
        textoCliente = new javax.swing.JComboBox<>();
        datoCliente = new javax.swing.JComboBox<>();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Ingresar.setBackground(new java.awt.Color(255, 255, 255));
        Ingresar.setFont(new java.awt.Font("Roboto Light", 0, 36)); // NOI18N
        Ingresar.setForeground(new java.awt.Color(255, 255, 255));
        Ingresar.setText("Ingresar >");
        Ingresar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Ingresar.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                IngresarMouseMoved(evt);
            }
        });
        Ingresar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                IngresarMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                IngresarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                IngresarMouseExited(evt);
            }
        });
        jPanel1.add(Ingresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 590, 170, 70));

        textoConstCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));
        jPanel1.add(textoConstCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        textoNombre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoNombreActionPerformed(evt);
            }
        });
        jPanel1.add(textoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 332, 200, 30));

        textoContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(textoContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 380, 200, 30));

        textoVerificacionContraseña.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoVerificacionContraseñaActionPerformed(evt);
            }
        });
        jPanel1.add(textoVerificacionContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 430, 200, 30));

        enviarNuevoUsuario.setFont(new java.awt.Font("Roboto Light", 0, 24)); // NOI18N
        enviarNuevoUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/BotonRegistrar.png"))); // NOI18N
        enviarNuevoUsuario.setContentAreaFilled(false);
        enviarNuevoUsuario.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/BotonRegistrar.png"))); // NOI18N
        enviarNuevoUsuario.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/BotonRegistrarGde.png"))); // NOI18N
        enviarNuevoUsuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarNuevoUsuarioMouseClicked(evt);
            }
        });
        enviarNuevoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enviarNuevoUsuarioActionPerformed(evt);
            }
        });
        jPanel1.add(enviarNuevoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 480, 420, 110));

        CuerpoCrearCuenta.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Creacion de Usuario.png"))); // NOI18N
        jPanel1.add(CuerpoCrearCuenta, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 820));

        textoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));
        textoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textoClienteActionPerformed(evt);
            }
        });
        jPanel1.add(textoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 480, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 20, 500, 660));

        datoCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cliente" }));
        datoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                datoClienteActionPerformed(evt);
            }
        });
        getContentPane().add(datoCliente, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 620, 90, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -20, 590, 730));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void enviarNuevoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enviarNuevoUsuarioActionPerformed
        // TODO add your handling code here:
        Funciones funcion = new Funciones();
        funcion.guardarDatos(textoNombre, textoContraseña, textoVerificacionContraseña, textoCliente);
        RegresarInicio();
    }//GEN-LAST:event_enviarNuevoUsuarioActionPerformed

    private void enviarNuevoUsuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarNuevoUsuarioMouseClicked
        // TODO add your handling code here:


    }//GEN-LAST:event_enviarNuevoUsuarioMouseClicked

    private void textoNombreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoNombreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoNombreActionPerformed

    private void textoVerificacionContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoVerificacionContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoVerificacionContraseñaActionPerformed

    private void IngresarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseClicked
        // TODO add your handling code here:
        //Volver al inicio sin crear usuario
        RegresarInicio();
    }//GEN-LAST:event_IngresarMouseClicked

    private void IngresarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseExited
        // TODO add your handling code here:
        // Quitar el Subrayado:      
        Font font = Ingresar.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, -1);
        Ingresar.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_IngresarMouseExited

    private void IngresarMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseMoved
        // TODO add your handling code here:
        //Subrayar texto ya tienes usuario
        Font font = Ingresar.getFont();
        Map attributes = font.getAttributes();
        attributes.put(TextAttribute.UNDERLINE, TextAttribute.UNDERLINE_ON);
        Ingresar.setFont(font.deriveFont(attributes));
    }//GEN-LAST:event_IngresarMouseMoved

    private void IngresarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_IngresarMouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_IngresarMouseEntered

    private void textoContraseñaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoContraseñaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoContraseñaActionPerformed

    private void datoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_datoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_datoClienteActionPerformed

    private void textoClienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textoClienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textoClienteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreacionUsuarioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreacionUsuarioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreacionUsuarioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreacionUsuarioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreacionUsuarioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel CuerpoCrearCuenta;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel Ingresar;
    private javax.swing.JComboBox<String> datoCliente;
    private javax.swing.JButton enviarNuevoUsuario;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JComboBox<String> textoCliente;
    private javax.swing.JComboBox<String> textoConstCliente;
    private javax.swing.JTextField textoContraseña;
    private javax.swing.JTextField textoNombre;
    private javax.swing.JTextField textoVerificacionContraseña;
    // End of variables declaration//GEN-END:variables
}
