/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectofinal;

/**
 *
 * @author mende
 */
public class PanelUsuarios extends javax.swing.JPanel {

    /**
     * Creates new form PanelUsuarios
     */
    public PanelUsuarios() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        CampoCodigo = new javax.swing.JTextField();
        CampoNombre = new javax.swing.JTextField();
        CampoApellidos = new javax.swing.JTextField();
        CampoCedula = new javax.swing.JTextField();
        CampoFecha = new javax.swing.JTextField();
        FondoRegistroUsuarios = new javax.swing.JLabel();
        TablaUsuarios = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        Fondo = new javax.swing.JLabel();

        setMinimumSize(new java.awt.Dimension(990, 460));
        setPreferredSize(new java.awt.Dimension(990, 460));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(246, 104, 68));
        jButton1.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Registrar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 380, 140, 50));
        add(CampoCodigo, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, 320, 30));
        add(CampoNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 160, 320, 30));
        add(CampoApellidos, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 320, 30));
        add(CampoCedula, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 270, 320, 30));
        add(CampoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 330, 320, 30));

        FondoRegistroUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        FondoRegistroUsuarios.setIcon(new javax.swing.ImageIcon("C:\\Users\\mende\\OneDrive\\Documentos\\GitHub\\ProgramacionCliente-Servidor\\ProyectoFinal\\Imagenes\\Registro de Usuarios.png")); // NOI18N
        add(FondoRegistroUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 20, -1, -1));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TablaUsuarios.setViewportView(jTable1);

        add(TablaUsuarios, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 400, 360));

        Fondo.setIcon(new javax.swing.ImageIcon("C:\\Users\\mende\\OneDrive\\Documentos\\GitHub\\ProgramacionCliente-Servidor\\ProyectoFinal\\Imagenes\\Fondo.png")); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CampoApellidos;
    private javax.swing.JTextField CampoCedula;
    private javax.swing.JTextField CampoCodigo;
    private javax.swing.JTextField CampoFecha;
    private javax.swing.JTextField CampoNombre;
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoRegistroUsuarios;
    private javax.swing.JScrollPane TablaUsuarios;
    private javax.swing.JButton jButton1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
