/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.proyectofinal;

/**
 *
 * @author mende
 */
public class PanelHorarioCliente extends javax.swing.JFrame {

    /**
     * Creates new form PanelHorario
     */
    public PanelHorarioCliente() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botonInscribirse = new javax.swing.JButton();
        campoClase = new javax.swing.JTextField();
        campoInstructor = new javax.swing.JTextField();
        campoHoraFin = new javax.swing.JTextField();
        campoHoraIn = new javax.swing.JTextField();
        campoFecha = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        FondoHorario = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        botonInscribirse.setBackground(new java.awt.Color(246, 104, 68));
        botonInscribirse.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        botonInscribirse.setForeground(new java.awt.Color(255, 255, 255));
        botonInscribirse.setText("Inscribirse");
        getContentPane().add(botonInscribirse, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 370, 210, 50));

        campoClase.setFocusable(false);
        getContentPane().add(campoClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 290, 30));

        campoInstructor.setFocusable(false);
        getContentPane().add(campoInstructor, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 260, 290, 30));

        campoHoraFin.setFocusable(false);
        getContentPane().add(campoHoraFin, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 200, 290, 30));

        campoHoraIn.setFocusable(false);
        getContentPane().add(campoHoraIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 140, 290, 30));

        campoFecha.setFocusable(false);
        getContentPane().add(campoFecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 90, 290, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 430, -1));

        FondoHorario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Horario Cliente.png"))); // NOI18N
        getContentPane().add(FondoHorario, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 520, -1));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Fondo.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PanelHorarioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PanelHorarioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PanelHorarioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PanelHorarioCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PanelHorarioCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoHorario;
    private javax.swing.JButton botonInscribirse;
    private javax.swing.JTextField campoClase;
    private javax.swing.JTextField campoFecha;
    private javax.swing.JTextField campoHoraFin;
    private javax.swing.JTextField campoHoraIn;
    private javax.swing.JTextField campoInstructor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
