/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.proyectofinal.InterfazCliente;

import com.mycompany.proyectofinal.InterfazEmpleado.*;
import com.mycompany.proyectofinal.InfoClase;
import java.sql.SQLException;
import javax.swing.table.DefaultTableModel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author shang
 */
public class PanelClaseCliente extends javax.swing.JPanel {

    /**
     * Creates new form clase
     */
    public PanelClaseCliente() {
        initComponents();
        llenarTabla();
        desabilitados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablaInstructores = new javax.swing.JScrollPane();
        tablaClaseCliente = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnSeleccionar = new javax.swing.JButton();
        txtoNombreClase = new javax.swing.JLabel();
        txtNombreClase = new javax.swing.JTextField();
        txtDesc = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JTextField();
        txtCupoMax = new javax.swing.JLabel();
        txtCupoMaximo = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        FondoPeq = new javax.swing.JLabel();
        lbid = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaClaseCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "NOMBRE DE CLASE", "DESCRIPCION", "CUPO MAXIMO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tablaClaseCliente.getTableHeader().setReorderingAllowed(false);
        tablaClaseCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaClaseClienteMouseClicked(evt);
            }
        });
        TablaInstructores.setViewportView(tablaClaseCliente);
        if (tablaClaseCliente.getColumnModel().getColumnCount() > 0) {
            tablaClaseCliente.getColumnModel().getColumn(0).setHeaderValue("NOMBRE DE CLASE");
            tablaClaseCliente.getColumnModel().getColumn(1).setHeaderValue("DESCRIPCION");
            tablaClaseCliente.getColumnModel().getColumn(2).setHeaderValue("CUPO MAXIMO");
        }

        add(TablaInstructores, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 647, 430));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnSeleccionar.setBackground(new java.awt.Color(255, 153, 51));
        btnSeleccionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Boton Seleccionar.png"))); // NOI18N
        btnSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSeleccionarActionPerformed(evt);
            }
        });
        jPanel1.add(btnSeleccionar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 120, 40));

        txtoNombreClase.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtoNombreClase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Nombre Clase.png"))); // NOI18N
        jPanel1.add(txtoNombreClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, -1, -1));
        jPanel1.add(txtNombreClase, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 290, 30));

        txtDesc.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtDesc.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Descripción.png"))); // NOI18N
        jPanel1.add(txtDesc, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 140, -1, -1));
        jPanel1.add(txtDescripcion, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 290, 30));

        txtCupoMax.setFont(new java.awt.Font("Gill Sans MT", 1, 14)); // NOI18N
        txtCupoMax.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Cupo Maximo.png"))); // NOI18N
        jPanel1.add(txtCupoMax, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, -1, -1));
        jPanel1.add(txtCupoMaximo, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 290, 30));

        btnRegistrar.setBackground(new java.awt.Color(246, 104, 68));
        btnRegistrar.setFont(new java.awt.Font("Eras Demi ITC", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Boton Registrar_.png"))); // NOI18N
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 330, 140, 40));

        FondoPeq.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Fondo.png"))); // NOI18N
        jPanel1.add(FondoPeq, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 300, 400));
        jPanel1.add(lbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 320, 40, 50));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 40, -1, 380));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/mycompany/imagenes/Fondo.png"))); // NOI18N
        add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 990, 460));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSeleccionarActionPerformed
        // TODO add your handling code here:
        int filaSeleccionada = tablaClaseCliente.getSelectedRow();
        if (filaSeleccionada != -1) {
            // Obtener los valores de la fila seleccionada
            int idClase = (int) tablaClaseCliente.getValueAt(filaSeleccionada, 0);
            String nombre = (String) tablaClaseCliente.getValueAt(filaSeleccionada, 1);
            String descripcion = (String) tablaClaseCliente.getValueAt(filaSeleccionada, 2);
            int cupoMaximo = (int) tablaClaseCliente.getValueAt(filaSeleccionada, 3);
            lbid.setText(String.valueOf(idClase));
            txtNombreClase.setText(nombre);
            txtDescripcion.setText(descripcion);
            txtCupoMaximo.setText(String.valueOf(cupoMaximo));
        } else {
            // Si no hay fila seleccionada, muestra un mensaje de error
            JOptionPane.showMessageDialog(null, "Selecciona una fila Para Acutalizar.");
        }
    }//GEN-LAST:event_btnSeleccionarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
    try {
            if (btnSeleccionar.isSelected()) {
                insertaDatos();
            } else {
                JOptionPane.showMessageDialog(null, "Debe Selecionar una Accion");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void tablaClaseClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaClaseClienteMouseClicked
        // TODO add your handling code here:
        int fila = tablaClaseCliente.rowAtPoint(evt.getPoint());
        txtNombreClase.setText(tablaClaseCliente.getValueAt(fila, 1).toString());
        txtDescripcion.setText(tablaClaseCliente.getValueAt(fila, 2).toString());
        txtCupoMaximo.setText(tablaClaseCliente.getValueAt(fila, 3).toString());
    }//GEN-LAST:event_tablaClaseClienteMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FondoPeq;
    private javax.swing.JScrollPane TablaInstructores;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSeleccionar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbid;
    private javax.swing.JTable tablaClaseCliente;
    private javax.swing.JLabel txtCupoMax;
    private javax.swing.JTextField txtCupoMaximo;
    private javax.swing.JLabel txtDesc;
    private javax.swing.JTextField txtDescripcion;
    private javax.swing.JTextField txtNombreClase;
    private javax.swing.JLabel txtoNombreClase;
    // End of variables declaration//GEN-END:variables
InfoClase infoclase = new InfoClase();

    public void llenarTabla() {
        InfoClase f = new InfoClase();
        try {
            // Llamar a la función consultarTodos() de FuncionesEstudiante
            DefaultTableModel model = f.consultarTodosParaTabla();

            // Actualizar la tabla con los datos obtenidos de la consulta
            tablaClaseCliente.setModel(model);
        } catch (SQLException ex) {
            ex.printStackTrace();
            // Aquí puedes agregar algún mensaje de error en caso de que ocurra un problema con la consulta
        }
    }

    public void insertaDatos() {
        try {
            String nombre = txtNombreClase.getText();
            String descripcion = txtDescripcion.getText();
            int cupo = Integer.parseInt(txtCupoMaximo.getText());
            int opcion = JOptionPane.showConfirmDialog(null, "¿Esta seguro de insertar estos datos?",
                    "Confirmación de inserción", JOptionPane.YES_NO_OPTION);
            if (opcion == JOptionPane.YES_OPTION) {
                infoclase.insertarClase(nombre, descripcion, cupo);
                llenarTabla();
                limpiar();
                JOptionPane.showMessageDialog(null, "Registro Insertado");
            } else {
                JOptionPane.showMessageDialog(null, "Inserción cancelada.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Formato de datos no valido");
            e.printStackTrace();
        }
    }

    public void ModificarDatos() {
        try {
            String nombre = txtNombreClase.getText();
            String descripcion = txtDescripcion.getText();
            int cupo = Integer.parseInt(txtCupoMaximo.getText());
            int id = Integer.parseInt(lbid.getText());
            int opcion = JOptionPane.showConfirmDialog(null, "¿Esta seguro de actualizar estos datos?",
                    "Confirmación de actualización", JOptionPane.YES_NO_OPTION);

            if (opcion == JOptionPane.YES_OPTION) {
                infoclase.modificarClase(nombre, descripcion, cupo, id);
                llenarTabla();
                limpiar();
                JOptionPane.showMessageDialog(null, "Registro Actualizado");
            } else {
                JOptionPane.showMessageDialog(null, "Actualización cancelada.");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Formato de datos no valido");
            e.printStackTrace();
        }
    }

    public void limpiar() {
        lbid.setText(String.valueOf(0));
        txtNombreClase.setText("");
        txtDescripcion.setText("");
        txtCupoMaximo.setText(String.valueOf(""));
    }

    public void desabilitados() {
        lbid.setText(String.valueOf(0));
        txtNombreClase.setEnabled(false);
        txtDescripcion.setEnabled(false);
        txtCupoMaximo.setEnabled(false);
    }

    public void habilitado() {
        btnRegistrar.setEnabled(true);
    }

}

